SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS users_reports;
DROP TABLE IF EXISTS users_blogs;
DROP TABLE IF EXISTS users_articles;
DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS blogs_categories;
DROP TABLE IF EXISTS notifs;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS themes;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE users (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lastname VARCHAR(150) NOT NULL,
  firstname VARCHAR(150) NOT NULL,
  pseudo VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  bio VARCHAR(500) NULL,
  profile_picture VARCHAR(255) NULL,
  status ENUM('active','inactive') DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(50) NOT NULL
);

CREATE TABLE categories (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE themes (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(100) NOT NULL,
  color_name VARCHAR(50) NOT NULL,
  font_name VARCHAR(100) NOT NULL,
  bg_image VARCHAR(255) NOT NULL
);

CREATE TABLE reports (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  report_reason ENUM('spam','bully','inappropriate','copyright'),
  description VARCHAR(255) NOT NULL,
  status ENUM('active', 'inactive') DEFAULT 'active',
  report_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blogs (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description VARCHAR(255) NOT NULL,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  theme_id INT(11) UNSIGNED NOT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (theme_id) REFERENCES themes(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE articles (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  content_text VARCHAR(255) NULL,
  content_image VARCHAR(255) NULL,
  release_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  status ENUM('published','draft') NULL,
  blog_id INT(11) UNSIGNED NOT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(200) NOT NULL,
  comment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  moderation_status ENUM('pending','approved','reported','rejected') NULL,
  article_id INT(11) UNSIGNED NOT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notifs (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  read_date DATETIME NULL,
  notif_type ENUM('comment','new_post') NOT NULL,
  comment_id INT(11) UNSIGNED NULL,
  article_id INT(11) UNSIGNED NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE blogs_categories (
  blog_id INT(11) UNSIGNED NOT NULL,
  categorie_id INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (blog_id, categorie_id),
  FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE,
  FOREIGN KEY (categorie_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE users_roles (
  user_id INT(11) UNSIGNED NOT NULL,
  role_id INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE users_articles (
  user_id INT(11) UNSIGNED NOT NULL,
  article_id INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, article_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE TABLE users_blogs (
  user_id INT(11) UNSIGNED NOT NULL,
  blog_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE
);

CREATE TABLE users_reports (
  user_id INT(11) UNSIGNED NOT NULL,
  article_id INT(11) UNSIGNED NULL,
  blog_id INT(11) UNSIGNED NULL,
  comment_id INT(11) UNSIGNED NULL,
  report_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE,
  FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
  FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE
);